libs =
#import libs += libhello%lib{hello}#

# ./ means "when building this dir, also build following target"
# executable linc depends on utility library linc, main.cxx.
# linc.testscript is associated with the linc executable
./: exe{linc}: libue{linc} {cxx}{main} testscript{linc}

# Utility library used by linc executable and
# the unit test executables
# Depends on hxx and cxx files in this directory
# except those who have .test.<something> in their name
# and those who are called main.
# Also depends on the libs
libue{linc}: {hxx cxx}{** -**.test... -main} $libs


# All executables ending with .test are tests.
# So they are built and executed with `b test`.
# They are also not installed with `b install`.
exe{*.test}:
{
  test = true
  install = false
}

# All files ending with <somename>.test.cxx should be compiled
# to executables <somename>.test
# They depend on <somename>.test.hxx, <somename>.test.ixx, <somename>.test.txx
# If <somename>.test.testscript exist, it is associated with the test executable
# bin.whole = false makes so only the used functions are statically linked
# into the test executable
for t: cxx{**.test...}
{
  d = $directory($t)
  n = $name($t)...

  ./: $d/exe{$n}: $t $d/{hxx ixx txx}{+$n} $d/testscript{+$n}
  $d/exe{$n}: libue{linc}: bin.whole = false
}

# Include our own header files
cxx.poptions =+ "-I$out_root" "-I$src_root"
# Include headers from PrusaSlicer
#cxx.poptions =+ "-I$src_root/../extern/prusaSlicer"
# Include headers for the headers-only eigen library
# These are needed by PrusaSlicer...
cxx.poptions =+ "-I$src_root/../extern/eigen"

# Follow cpp core guidelines
cxx.poptions =+ "-I$src_root/../extern/cppcore"
